-- ============================================================
-- MIGRATION 012: notification_dismissals
-- Persists admin notification dismissals as individual rows.
-- Each alert_key is unique (period-scoped), so dismissing
-- "vehicle-payment-2-2026-06" in June stays dismissed in June
-- but naturally re-fires in July with a fresh key.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.notification_dismissals (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  alert_key    TEXT        NOT NULL UNIQUE,
  dismissed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  dismissed_by UUID        REFERENCES auth.users(id)
);

COMMENT ON TABLE  public.notification_dismissals           IS 'One row per dismissed notification alert_key. alert_key is period-scoped (e.g. vehicle-payment-2-2026-06) so it re-fires naturally in future periods.';
COMMENT ON COLUMN public.notification_dismissals.alert_key IS 'Deterministic composite key matching the notification id generated by computeNotifications().';

ALTER TABLE public.notification_dismissals ENABLE ROW LEVEL SECURITY;

-- Admin can read and write all dismissals
CREATE POLICY "notification_dismissals: admin all"
  ON public.notification_dismissals FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- All authenticated users can read (for future member dismissals if needed)
CREATE POLICY "notification_dismissals: authenticated read"
  ON public.notification_dismissals FOR SELECT
  USING (auth.role() = 'authenticated');
